CREATE TABLE 'users' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'firstName' TEXT DEFAULT NULL,
'lastName' TEXT DEFAULT NULL,
'phone' TEXT DEFAULT NULL,
'passwordHash' TEXT DEFAULT NULL,
'idRole' INTEGER DEFAULT NULL REFERENCES 'roles' ('id'),
'dateCreated' TEXT DEFAULT NULL
);

CREATE TABLE 'categories' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'name' TEXT DEFAULT NULL,
'description' TEXT DEFAULT NULL
);

CREATE TABLE 'equipment' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'idCategory' INTEGER DEFAULT NULL REFERENCES 'categories' ('id'),
'idBrand' INTEGER DEFAULT NULL REFERENCES 'brands' ('id'),
'idType' INTEGER DEFAULT NULL REFERENCES 'equipmentType' ('id'),
'title' TEXT DEFAULT NULL,
'description' TEXT DEFAULT NULL,
'model' TEXT DEFAULT NULL
);

CREATE TABLE 'rentOrders' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'idUser' INTEGER DEFAULT NULL REFERENCES 'users' ('id'),
'idstatus' INTEGER DEFAULT NULL REFERENCES 'orderStatus' ('id'),
'dateCreated' TEXT DEFAULT NULL,
'dateStart' TEXT DEFAULT NULL,
'dateEnd' TEXT DEFAULT NULL,
'amount' TEXT DEFAULT NULL,
'depositAmount' TEXT DEFAULT NULL,
'comment' TEXT DEFAULT NULL
);

CREATE TABLE 'orderItems' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'idOrder' TEXT DEFAULT NULL REFERENCES 'rentOrders' ('id'),
'idEquipment' TEXT DEFAULT NULL REFERENCES 'equipment' ('id'),
'quantity' TEXT DEFAULT NULL,
'pricePerUnit' REAL DEFAULT NULL,
'amount' REAL DEFAULT NULL
);

CREATE TABLE 'payments' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'idOrder' INTEGER DEFAULT NULL REFERENCES 'rentOrders' ('id'),
'idMethod' INTEGER DEFAULT NULL REFERENCES 'paymentMethods' ('id'),
'idStatus' INTEGER DEFAULT NULL REFERENCES 'paymentStatuses' ('id'),
'dateCreated' TEXT DEFAULT NULL,
'amount' REAL DEFAULT NULL
);

CREATE TABLE 'rentalPoints' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'name' TEXT DEFAULT NULL,
'address' TEXT DEFAULT NULL,
'phone' TEXT DEFAULT NULL
);

CREATE TABLE 'paymentStatuses' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'title' TEXT DEFAULT NULL
);

CREATE TABLE 'paymentMethods' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'title' TEXT DEFAULT NULL
);

CREATE TABLE 'orderStatus' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'title' TEXT DEFAULT NULL
);

CREATE TABLE 'roles' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'title' TEXT DEFAULT NULL
);

CREATE TABLE 'equipmentConditions' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'title' TEXT DEFAULT NULL
);

CREATE TABLE 'rentalTypes' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'title' TEXT DEFAULT NULL,
'code' TEXT DEFAULT NULL,
'unitHours' INTEGER DEFAULT NULL
);

CREATE TABLE 'equipmentRates' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'idEquipment' INTEGER DEFAULT NULL REFERENCES 'equipment' ('id'),
'idRentalType' INTEGER DEFAULT NULL REFERENCES 'rentalTypes' ('id'),
'price' REAL DEFAULT NULL,
'deposit' REAL DEFAULT NULL
);

CREATE TABLE 'rentalPointEquipment' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'idRentalPoint' INTEGER DEFAULT NULL REFERENCES 'rentalPoints' ('id'),
'idEquipment' INTEGER DEFAULT NULL REFERENCES 'equipment' ('id'),
'idEquipmentCondition' INTEGER DEFAULT NULL REFERENCES 'equipmentConditions' ('id'),
'idSize' INTEGER DEFAULT NULL REFERENCES 'equipmentSizes' ('id'),
'totalQuantity' INTEGER DEFAULT NULL,
'availableQuantity' INTEGER DEFAULT NULL
);

CREATE TABLE 'brands' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'title' TEXT DEFAULT NULL
);

CREATE TABLE 'equipmentType' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'title' TEXT DEFAULT NULL
);

CREATE TABLE 'images' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'url' TEXT DEFAULT NULL,
'dateCreated' TEXT DEFAULT NULL
);

CREATE TABLE 'equipmentPhotos' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'idEquipment' INTEGER DEFAULT NULL REFERENCES 'equipment' ('id'),
'idImage' INTEGER DEFAULT NULL REFERENCES 'images' ('id')
);

CREATE TABLE 'equipmentSizes' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'title' TEXT DEFAULT NULL
);